baseurl = "/"
languageCode = "en-us"
theme = "hugo-theme-terminal"
paginate = 5

[params]
  contentTypeName = "posts"
  themeColor = "orange"

[params.logo]
  logoText = "terminal"

[languages]
  [languages.en]
    title = "Terminal"
    subtitle = "A simple, retro theme for Hugo"
    keywords = ""
    copyright = ""
    readMore = "Read more"
    readOtherPosts = "Read other posts"

    [languages.en.params.logo]
      logoText = "terminal"
      logoHomeLink = "/"

    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "about"
        name = "About"
        url = "/about"
      [[languages.en.menu.main]]
        identifier = "showcase"
        name = "Showcase"
        url = "/showcase"
